[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "mllogs"
version = "0.1.4"
description = "Local experiment logging for machine learning"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [
    { name = "Finn Walsh" }
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
]